local assert = require("tests.helpers.assert")
local addonName, ns, loaded = assert.load_addon_from_toc("GBankManager/GBankManager.toc")

assert.equal("GBankManager", addonName, "toc should load the addon by name")
assert.equal("GBankManager", ns.addonName, "namespace should expose addon name")
assert.truthy(type(ns.modules) == "table", "namespace should expose module table")
assert.truthy(type(ns.state) == "table", "namespace should expose state table")
assert.truthy(type(ns.constants) == "table", "constants should populate the shared namespace")
assert.equal(1, ns.constants.SCHEMA_VERSION, "constants should expose schema version")
assert.truthy(type(ns.modules.events) == "table", "events module should populate the shared namespace")
assert.truthy(type(ns.modules.slash) == "table", "slash module should populate the shared namespace")
assert.same(ns, loaded[1].value, "namespace chunk should return the shared namespace table")
assert.same(ns.modules.events, loaded[4].value, "events chunk should return the shared events module")
assert.same(ns.modules.slash, loaded[5].value, "slash chunk should return the shared slash module")
