local assert = require("tests.helpers.assert")
local fixture = require("tests.helpers.ui_fixture")

dofile("tests/helpers/wow_stubs.lua")

local env = fixture.load()
local mainFrame = env.mainFrame
local slash = env.slash
local scanner = env.scanner
local themeManager = env.ns.modules.themeManager
local syncEvents = env.ns.modules.syncEvents
local minimapButton = env.ns.modules.minimapButton
local activeTheme = env.mainFrameShell.GetTheme()

assert.truthy(type(mainFrame.closeButton) == "table", "main frame should expose a close button")
assert.truthy(type(mainFrame.collapseButton) == "table", "main frame should expose a collapse control")
assert.truthy(type(mainFrame.scanButton) == "table", "main frame should expose a scan button")
assert.truthy(type(themeManager) == "table", "ui shell should register a shared theme manager")
assert.equal("generic_wow", (_G.GBankManagerDB.ui.appearance or {}).themePreset, "ui shell should keep the internal default preset key stable")
assert.equal("generic_wow", mainFrame.appearanceThemePreset, "ui shell should load the migrated default preset into the shell state")
assert.equal("Default", ((themeManager.GetTheme("generic_wow") or {}).label or ""), "theme manager should expose the Default preset")
assert.equal("High Contrast", ((themeManager.GetTheme("high_contrast") or {}).label or ""), "theme manager should expose the High Contrast preset")
assert.equal("Nature", ((themeManager.GetTheme("nature") or {}).label or ""), "theme manager should expose the Nature preset")
assert.equal("Legion", ((themeManager.GetTheme("legion") or {}).label or ""), "theme manager should expose the Legion preset")
assert.equal("Pride", ((themeManager.GetTheme("pride") or {}).label or ""), "theme manager should expose the Pride preset")
assert.equal("generic_wow", themeManager.NormalizePresetKey("default"), "theme manager should migrate the old default preset key")
assert.equal("high_contrast", themeManager.NormalizePresetKey("contrast"), "theme manager should migrate the old contrast preset key")
assert.equal("nature", themeManager.NormalizePresetKey("moonglade"), "theme manager should migrate the old moonglade preset key")
assert.equal("legion", themeManager.NormalizePresetKey("fel"), "theme manager should normalize the fel alias to Legion")
assert.truthy(type(mainFrame.sidebarButtons[1]:GetScript("OnClick")) == "function", "sidebar buttons should switch views when clicked")
assert.equal("Interface\\AddOns\\GBankManager\\Art\\GBM_Logo_Default.png", mainFrame.sidebarCrestTexture.texture, "sidebar crest should use the supplied Default logo art")
assert.equal("Interface\\AddOns\\GBankManager\\Art\\GBM_Logo_Default.png", mainFrame.aboutCrestTexture.texture, "about panel should reuse the supplied Default logo art")
assert.truthy(type(mainFrame.sidebarCrestTexture.texCoord) == "table", "sidebar crest should crop padded logo art with tex coords")
assert.truthy((mainFrame.sidebarCrestTexture.texCoord[1] or 0) > 0.05, "sidebar crest should trim transparent left padding from the logo art")
assert.truthy((mainFrame.sidebarCrestTexture.texCoord[2] or 1) < 0.95, "sidebar crest should trim transparent right padding from the logo art")
assert.truthy((mainFrame.sidebarCrestTexture.texCoord[3] or 0) > 0.05, "sidebar crest should trim transparent top padding from the logo art")
assert.truthy((mainFrame.sidebarCrestTexture.texCoord[4] or 1) < 0.95, "sidebar crest should trim transparent bottom padding from the logo art")
assert.truthy((mainFrame.sidebarCrestTexture.width or 0) >= 120, "sidebar crest should expand into the footer zone instead of staying as a tiny top icon")
assert.same(mainFrame.sidebarIdentityPanel, mainFrame.sidebarCrestTexture:GetParent(), "sidebar crest should be parented to the footer panel so the panel does not occlude it")
assert.same(mainFrame.sidebarIdentityPanel, (mainFrame.sidebarCrestTexture.points[1] or {})[2], "sidebar crest should anchor into the footer panel zone")
assert.equal(mainFrame.sidebarCrestTexture.width or 0, mainFrame.sidebarCrestTexture.height or 0, "expanded sidebar crest should preserve the supplied square art ratio")
assert.truthy((mainFrame.sidebarCrestTexture.height or 0) >= (((mainFrame.sidebarIdentityPanel:GetHeight() or 0) - 10)), "expanded sidebar crest should still fill most of the footer panel height")
assert.equal(0, (((mainFrame.sidebarIdentityPanel or {}).backdropColor or {})[4] or 0), "sidebar crest zone should not draw a footer background box")
assert.equal(0, (((mainFrame.sidebarIdentityPanel or {}).backdropBorderColor or {})[4] or 0), "sidebar crest zone should not draw a footer border box")
assert.truthy((select(5, mainFrame.sidebarButtons[1]:GetPoint(1)) or 0) >= -60, "sidebar nav rows should move back toward the top once the crest leaves the header area")
assert.truthy(type(mainFrame.sidebarButtons[1].navIcon) == "table", "sidebar buttons should expose nav icons for collapsed navigation")
assert.truthy(mainFrame.sidebarButtons[1].navIcon.texture ~= nil, "sidebar buttons should assign a nav icon texture")
assert.equal("Interface\\ICONS\\icon_treasuremap", mainFrame.sidebarButtons[1].navIcon.texture, "dashboard should use the treasure map icon")
assert.equal("Interface\\ICONS\\item_bastion_paragonchest_01", mainFrame.sidebarButtons[2].navIcon.texture, "inventory should use the requested chest icon")
assert.equal("Interface\\ICONS\\inv_10_fishing_dragonislescoins_gold", mainFrame.sidebarButtons[3].navIcon.texture, "minimums should use the coin icon")
assert.equal("Interface\\ICONS\\achievement_guildperk_gmail", mainFrame.sidebarButtons[4].navIcon.texture, "requests should use the guild mail icon")
assert.equal("Interface\\ICONS\\achievement_guildperk_fasttrack", mainFrame.sidebarButtons[5].navIcon.texture, "exports should use the fast track icon")
assert.equal("Interface\\ICONS\\inv_10_inscription2_book1_color2", mainFrame.sidebarButtons[6].navIcon.texture, "history should use the inscription book icon")
assert.equal("Interface\\ICONS\\inv_misc_stonetablet_04", mainFrame.sidebarButtons[7].navIcon.texture, "bank ledger should use the stone tablet icon")
assert.equal("Interface\\ICONS\\inv_10_engineering_manufacturedparts_gear_frost", mainFrame.sidebarButtons[8].navIcon.texture, "options should use the engineering gear icon")
assert.equal("Interface\\ICONS\\inv_misc_scrollunrolled04b", mainFrame.sidebarButtons[9].navIcon.texture, "about should use the unrolled scroll icon")
assert.equal("shell", mainFrame.gbmSurfaceVariant, "main frame should use the shell surface variant")
assert.equal("sidebar-soft-row", mainFrame.sidebarNavStyle, "shell should expose the softer nav-row styling contract")
assert.equal("toolbar-band", mainFrame.headerStyle, "shell should expose the clean toolbar-band header contract")
assert.equal("flat-band", mainFrame.contentSectionStyle, "shell should expose the flatter content-band contract")
assert.equal("sidebar", (mainFrame.sidebar or {}).gbmSurfaceVariant, "sidebar should still use the shared sidebar surface variant")
assert.equal("header-toolbar", (mainFrame.topBar or {}).gbmSurfaceVariant, "top bar should move to the toolbar-style header variant")
assert.equal("content-band", (mainFrame.content or {}).gbmSurfaceVariant, "main content should move to the flatter content-band variant")
assert.equal(0, (((mainFrame.topBar or {}).backdropBorderColor or {})[4] or 0), "toolbar-band header should not rely on a full backdrop border")
assert.equal(0, (((mainFrame.content or {}).backdropBorderColor or {})[4] or 0), "content band should not rely on a full backdrop border")
assert.equal("nav", (mainFrame.sidebarButtons[1] or {}).gbmButtonVariant, "sidebar buttons should use the dedicated nav button variant")
assert.equal(0, ((((mainFrame.sidebarButtons or {})[1] or {}).backdropBorderColor or {})[4] or 0), "soft nav buttons should not rely on a full backdrop border")
assert.equal("metric-card-flat", ((mainFrame.dashboardCards or {})[1] or {}).gbmSurfaceVariant, "dashboard cards should use the flatter metric-card surface variant")
assert.equal("panel-flat", (mainFrame.dashboardTopItemsPanel or {}).gbmSurfaceVariant, "dashboard support panels should use the flatter panel surface variant")
assert.equal(0, (((mainFrame.dashboardTopItemsPanel or {}).backdropBorderColor or {})[4] or 0), "flatter dashboard panels should not rely on a full backdrop border")
assert.equal("action-card", ((mainFrame.exportActionCards or {})[1] or {}).gbmSurfaceVariant, "export cards should use the action-card surface variant")
assert.truthy(type((mainFrame.gbmArt or {}).background) == "table", "main shell should expose a reusable art background texture")
assert.truthy(type(((mainFrame.sidebarButtons or {})[1] or {}).gbmArt) == "table", "nav buttons should expose reusable art layers")
assert.truthy(type((((mainFrame.sidebarButtons or {})[1] or {}).gbmArt or {}).accentBar) == "table", "nav buttons should expose an accent-bar art layer")
assert.truthy(type((((mainFrame.dashboardCards or {})[1] or {}).gbmArt or {}).headerBand) == "table", "dashboard cards should expose a shared header-band art layer")
assert.truthy(type(mainFrame.sidebarIdentityPanel) == "table", "sidebar should expose a footer crest panel")
assert.truthy(type(mainFrame.sidebarIdentityNameText) == "table", "sidebar should still keep the old identity labels available for compatibility")
assert.truthy(type(mainFrame.sidebarIdentityGuildText) == "table", "sidebar should still keep the old guild label available for compatibility")
assert.truthy(type(minimapButton) == "table", "ui shell should register a dedicated minimap-button module")
assert.truthy(type(minimapButton.button) == "table", "ui shell should create a minimap launcher button")
assert.equal("Interface\\AddOns\\GBankManager\\Art\\GBM_Minimap_Button.png", ((minimapButton.button or {}).icon or {}).texture, "minimap launcher should use the supplied minimap icon art")
assert.truthy(minimapButton.button:IsShown(), "minimap launcher should show by default")
assert.equal("HIGH", minimapButton.button.frameStrata, "minimap launcher should sit at a high enough strata to stay visible over the minimap")
assert.truthy(((_G.GBankManagerDB.ui.appearance or {}).minimapAngle or 0) >= 300, "minimap launcher should default to an upper-right minimap position instead of the older lower-left placement")
assert.equal("colored-distinct", mainFrame.themeExpressionStyle, "shell should expose the stronger colored-theme expression contract")
assert.equal("dense-clean", mainFrame.defaultDensityStyle, "shell should expose the dense-but-clean spacing contract")
assert.equal(0, ((mainFrame.sidebarButtons[1].backdropBorderColor or {})[4] or 0), "active sidebar view should no longer rely on a border glow")
assert.equal("nav-soft", (mainFrame.collapseButton or {}).gbmButtonFamily, "sidebar controls should use the softer nav-button family")
assert.equal("nav-soft", ((mainFrame.sidebarButtons or {})[1] or {}).gbmButtonFamily, "sidebar nav rows should use the softer distinct-button family")
assert.equal("selected-strong", ((mainFrame.sidebarButtons or {})[1] or {}).gbmSelectionStyle, "selected nav rows should expose the stronger active-state contract")
local headerStatusText = (mainFrame.statusText and mainFrame.statusText:GetText()) or ""
assert.truthy(string.find(headerStatusText, "EDT", 1, true) ~= nil or string.find(headerStatusText, "EST", 1, true) ~= nil or headerStatusText == "No scan yet", "header last-scan text should include a timezone abbreviation")
assert.truthy(string.find(headerStatusText, "Daylight", 1, true) == nil, "header last-scan text should avoid the long daylight-time label")
assert.truthy(string.find(headerStatusText, "Standard", 1, true) == nil, "header last-scan text should avoid the long standard-time label")
assert.truthy(string.find(headerStatusText, "Eastern", 1, true) == nil, "header last-scan text should use a short timezone abbreviation instead of the full timezone name")
assert.truthy(not ((mainFrame.topBar or {}).gbmArt or {}).topLine:IsShown(), "toolbar-band header should stop drawing a framed top edge")
assert.truthy(not ((mainFrame.topBar or {}).gbmArt or {}).leftLine:IsShown(), "toolbar-band header should stop drawing a framed left edge")
assert.truthy(not ((mainFrame.topBar or {}).gbmArt or {}).rightLine:IsShown(), "toolbar-band header should stop drawing a framed right edge")
assert.truthy(((mainFrame.topBar or {}).gbmArt or {}).bottomLine:IsShown(), "toolbar-band header should keep a bottom separator for structure")
assert.truthy(not ((mainFrame.topBar or {}).gbmArt or {}).headerBand:IsShown(), "toolbar-band header should not keep the older inset top strip")
assert.truthy(not ((mainFrame.content or {}).gbmArt or {}).topLine:IsShown(), "content-band should stop drawing an extra framed top edge")
assert.truthy(not ((mainFrame.content or {}).gbmArt or {}).leftLine:IsShown(), "content-band should stop drawing an extra framed left edge")
assert.truthy(not ((mainFrame.content or {}).gbmArt or {}).rightLine:IsShown(), "content-band should stop drawing an extra framed right edge")
assert.truthy(not ((mainFrame.content or {}).gbmArt or {}).bottomLine:IsShown(), "content-band should stop drawing an extra framed bottom edge")
assert.truthy(not (((mainFrame.dashboardTopItemsPanel or {}).gbmArt or {}).headerBand):IsShown(), "flatter dashboard panels should drop the inset header strip")
assert.truthy(not ((((mainFrame.dashboardCards or {})[1] or {}).gbmArt or {}).headerBand):IsShown(), "metric cards should flatten out and drop the inset header strip")
assert.truthy(not ((((mainFrame.sidebarButtons or {})[1] or {}).gbmArt or {}).headerBand):IsShown(), "soft nav buttons should not draw inset header-strip chrome")
assert.truthy(not (((mainFrame.dashboardTopItemsPanel or {}).gbmArt or {}).topLine:IsShown()), "flatter dashboard panels should avoid boxed top edges")
assert.truthy(not (((mainFrame.dashboardTopItemsPanel or {}).gbmArt or {}).leftLine:IsShown()), "flatter dashboard panels should avoid boxed left edges")
assert.truthy(not (((mainFrame.dashboardTopItemsPanel or {}).gbmArt or {}).rightLine:IsShown()), "flatter dashboard panels should avoid boxed right edges")
assert.truthy(not (((mainFrame.dashboardTopItemsPanel or {}).gbmArt or {}).bottomLine:IsShown()), "flatter dashboard panels should avoid boxed bottom edges")
assert.truthy(not ((((mainFrame.sidebarButtons or {})[1] or {}).gbmArt or {}).topLine:IsShown()), "soft nav buttons should avoid the older framed top edge")
assert.truthy(not ((((mainFrame.sidebarButtons or {})[1] or {}).gbmArt or {}).leftLine:IsShown()), "soft nav buttons should avoid the older framed left edge")
assert.truthy(not ((((mainFrame.sidebarButtons or {})[1] or {}).gbmArt or {}).rightLine:IsShown()), "soft nav buttons should avoid the older framed right edge")
assert.truthy(not ((((mainFrame.sidebarButtons or {})[1] or {}).gbmArt or {}).bottomLine:IsShown()), "soft nav buttons should avoid the older framed bottom edge")
assert.truthy(((((mainFrame.sidebarButtons or {})[1] or {}).gbmArt or {}).accentBar):IsShown(), "selected nav buttons should lean on the accent rail instead of boxed borders")
assert.truthy((mainFrame.topBar:GetHeight() or 0) <= 76, "toolbar-band header should stay visually slimmer than the older framed header")
assert.truthy((mainFrame.navButtonSpacing or 0) <= 42, "dense-clean spacing should reduce nav spacing from the roomier shell pass")
assert.truthy((((mainFrame.dashboardCards or {})[1] or {}):GetHeight() or 0) <= 104, "dense-clean spacing should keep metric cards substantial but not oversized")
assert.same(mainFrame.closeButton, (mainFrame.scanButton.points[1] or {})[2], "scan button should anchor from the close button side to avoid scaled-header overlap")
assert.same(mainFrame.scanButton, (mainFrame.statusText.points[1] or {})[2], "status text should anchor from the scan button side to avoid scaled-header overlap")
assert.equal(920, mainFrame.resizeBounds.minWidth, "main frame should keep the shell resize minimum width")
assert.equal(560, mainFrame.resizeBounds.minHeight, "main frame should keep the shell resize minimum height")

slash.command("ui")
assert.truthy(mainFrame:IsShown(), "slash ui command should show the main frame")
assert.truthy(mainFrame.mouseEnabled == true, "opening the main frame should enable mouse capture")
assert.truthy(mainFrame.topLevel == true, "main frame should opt into top-level window ordering")
assert.equal("MEDIUM", mainFrame.frameStrata, "main frame should sit below higher-priority Blizzard dialogs until refocused")

assert.truthy(not mainFrame.sidebarIdentityNameText:IsShown(), "sidebar footer should stop showing the character name text")
assert.truthy(not mainFrame.sidebarIdentityGuildText:IsShown(), "sidebar footer should stop showing the guild name text")

local originalFrameLevel = tonumber(mainFrame.frameLevel or 0) or 0
local onMouseDown = mainFrame:GetScript("OnMouseDown")
assert.truthy(type(onMouseDown) == "function", "main frame should expose a mouse-down front-focus handler")
onMouseDown(mainFrame)
assert.truthy((tonumber(mainFrame.frameLevel or 0) or 0) > originalFrameLevel, "clicking the shell should raise it in the local frame stack")

mainFrame.collapseButton:GetScript("OnClick")(mainFrame.collapseButton)
assert.truthy(mainFrame.collapsedSidebar == true, "toggle should collapse the sidebar")
assert.equal(40, mainFrame.sidebarButtons[1]:GetWidth(), "collapsed sidebar should shrink nav button width")
assert.equal("", mainFrame.sidebarButtons[1].labelText:GetText(), "collapsed sidebar should hide nav labels instead of stacking characters")
assert.truthy(mainFrame.sidebarButtons[1].navIcon.texture ~= nil, "collapsed sidebar should keep the nav icon visible")
assert.truthy(not mainFrame.sidebarIdentityNameText:IsShown(), "collapsed sidebar should keep the old footer identity text hidden")
assert.truthy(not mainFrame.sidebarIdentityPanel:IsShown(), "collapsed sidebar should hide the footer crest panel entirely")
assert.truthy(not mainFrame.sidebarCrestTexture:IsShown(), "collapsed sidebar should hide the footer crest entirely")

mainFrame:SetThemePreset("legion")
assert.equal("Interface\\AddOns\\GBankManager\\Art\\GBM_Logo_Fel.png", mainFrame.sidebarCrestTexture.texture, "Legion should swap in the Fel crest art")
mainFrame:SetThemePreset("pride")
assert.equal("Interface\\AddOns\\GBankManager\\Art\\GBM_Logo_Pride.png", mainFrame.sidebarCrestTexture.texture, "Pride should swap in the Pride crest art")
assert.truthy((((themeManager.GetTheme("pride") or {}).tokens or {}).accent or {})[1] >= 0.90, "Pride should lean into a brighter pink accent treatment")
assert.truthy((((themeManager.GetTheme("pride") or {}).tokens or {}).accent or {})[2] >= 0.40, "Pride should keep enough warmth in the accent to read pink instead of blue-purple")
assert.truthy((((themeManager.GetTheme("pride") or {}).tokens or {}).panelAlt or {})[1] >= 0.28, "Pride should brighten the panel surfaces enough to separate from the darker shell")
mainFrame:SetShowMinimapButton(false)
assert.truthy(not minimapButton.button:IsShown(), "appearance toggles should hide the minimap launcher")
mainFrame:SetShowMinimapButton(true)
assert.truthy(minimapButton.button:IsShown(), "appearance toggles should show the minimap launcher again")

local modal = mainFrame:OpenMinimumAddModal()
assert.truthy(type(modal) == "table", "minimum add modal should still open from the shared shell")
local raisedShellLevel = tonumber(mainFrame.frameLevel or 0) or 0
assert.equal(raisedShellLevel + 20, modal.frameLevel, "opened modals should layer above the current shell level")
onMouseDown(mainFrame)
assert.equal((tonumber(mainFrame.frameLevel or 0) or 0) + 20, modal.frameLevel, "raising the shell should keep registered modals above it")

scanner.scanInProgress = false
mainFrame.scanButton:GetScript("OnClick")(mainFrame.scanButton)
assert.truthy(type(mainFrame.scanButton:GetScript("OnClick")) == "function", "scan button should stay wired to the scanner entrypoint")
